tree: Events
eras:
  '2018':
    luminosity: 59740.565201546  
    luminosity-error: 0.025     
samples:
  TTToSemiLeptonic:
    db: das:/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8/RunIIAutumn18NanoAODv5-Nano1June2019_102X_upgrade2018_realistic_v19-v1/NANOAODSIM
    files: dascache/bTaggingEff/TTToSemiLeptonic_2018.dat
    generated-events: 'genEventSumw'
    cross-section:  365.34 #  +4.8%-6.1%  pb
    group: TTJets_SL
    era: '2018'
    split: 4
                                  
  TTToFullLeptonic:
    db: das:/TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8/RunIIAutumn18NanoAODv5-Nano1June2019_102X_upgrade2018_realistic_v19-v1/NANOAODSIM
    files: dascache/bTaggingEff/TTTo2L2Nu_2018.dat
    generated-events: 'genEventSumw'
    cross-section: 88.29 # +4.8%-6.1%  pb 
    group: TTJets_DL
    era: '2018'
    split: 4
  
  TTToHadronic:
    db: das:/TTToHadronic_TuneCP5_13TeV-powheg-pythia8/RunIIAutumn18NanoAODv5-Nano1June2019_102X_upgrade2018_realistic_v19-v1/NANOAODSIM
    files: dascache/bTaggingEff/TTHadronic_2018.dat
    generated-events: 'genEventSumw'
    cross-section: 687.1  # +- 0.5174 pb
    group: TTJets_AH
    era: '2018'
    split: 4
 
  ST_tW_top_5f:  
    db: das:/ST_tW_top_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8/RunIIAutumn18NanoAODv5-Nano1June2019_102X_upgrade2018_realistic_v19_ext1-v1/NANOAODSIM
    files: dascache/bTaggingEff/ST_tWtop_5f_2018.dat
    generated-events: 'genEventSumw'
    cross-section:  34.91 # +- 0.02817 pb 
    group: tW
    era: '2018'
    split: 4

  ST_tW_antitop_5f:   
    db: das:/ST_tW_antitop_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8/RunIIAutumn18NanoAODv5-Nano1June2019_102X_upgrade2018_realistic_v19_ext1-v1/NANOAODSIM
    files: dascache/bTaggingEff/ST_tWantitop_5f_2018.dat
    generated-events: 'genEventSumw'
    cross-section:    34.97 # +- 0.02827 pb
    group: atW
    era: '2018'
    split: 4


  DYJetsToLL_M-10to50-madgraphMLM:
    db: das:/DYJetsToLL_M-10to50_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIAutumn18NanoAODv5-Nano1June2019_102X_upgrade2018_realistic_v19-v1/NANOAODSIM
    files: dascache/bTaggingEff/DYJetsToLL_M-10to50-madgraphMLM_2018.dat
    generated-events: 'genEventSumw'
    cross-section: 15810 # +- 5.764 pb
    group: DY
    era: '2018'
    split: 4
    
        
  DYJetsToLL_M-50-madgraphMLM:
    db: das:/DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIAutumn18NanoAODv5-Nano1June2019_102X_upgrade2018_realistic_v19-v1/NANOAODSIM
    files: dascache/bTaggingEff/DYJetsToLL_M-50-madgraphMLM_2018.dat
    generated-events: 'genEventSumw'
    cross-section: 6225.42  #+- ? pb
    group: DY
    era: '2018'
    split: 4
  

  DYJetsToLL_M-50-amcatnloFXFX:
    db: das:[/DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIIAutumn18NanoAODv5-Nano1June2019_102X_upgrade2018_realistic_v19-v1/NANOAODSIM, /DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIIAutumn18NanoAODv5-Nano1June2019_102X_upgrade2018_realistic_v19_ext2-v1/NANOAODSIM]
    files: dascache/bTaggingEff/DYJetsToLL_M-50-amcatnloFXFX_2018.dat
    generated-events: 'genEventSumw'
    cross-section: 6529.0  # +- 28.29 pb 
    group: DY
    era: '2018'
    split: 4
    
  WW:
    db: das:/WW_TuneCP5_13TeV-pythia8/RunIIAutumn18NanoAODv5-Nano1June2019_102X_upgrade2018_realistic_v19-v1/NANOAODSIM      
    files: dascache/bTaggingEff/WW_2018.dat
    generated-events: 'genEventSumw'
    cross-section: 75.8 # +- 0.1123  pb
    group: WW
    era: '2018'
    split: 4
      

  WZ:
    db: das:/WZ_TuneCP5_13TeV-pythia8/RunIIAutumn18NanoAODv5-Nano1June2019_102X_upgrade2018_realistic_v19-v1/NANOAODSIM
    files: dascache/bTaggingEff/WZ_2018.dat
    generated-events: 'genEventSumw'
    cross-section: 27.6 # +- 0.04 pb
    group: WZ
    era: '2018'
    split: 4
    

  ZZ:
    db: das:/ZZ_TuneCP5_13TeV-pythia8/RunIIAutumn18NanoAODv5-Nano1June2019_102X_upgrade2018_realistic_v19-v1/NANOAODSIM 
    files: dascache/bTaggingEff/ZZ_2018.dat
    generated-events: 'genEventSumw'
    cross-section: 12.14 # +- 0.01964 pb
    group: ZZ
    era: '2018'
    split: 4

  W2JetsToLNu:
    db: das:/W2JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIAutumn18NanoAODv5-Nano1June2019_102X_upgrade2018_realistic_v19-v1/NANOAODSIM 
    files: dascache/bTaggingEff/W2JetsToLNu_2018.dat
    generated-events: 'genEventSumw'
    cross-section: 2793.0 # +-8.074 pb 
    group: WPLusJets
    era: '2018'
    split: 4
    
    
  W3JetsToLNu:
    db: das:/W3JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIAutumn18NanoAODv5-Nano1June2019_102X_upgrade2018_realistic_v19-v1/NANOAODSIM
    files: dascache/bTaggingEff/W3JetsToLNu_2018.dat
    generated-events: 'genEventSumw'
    cross-section: 992.5 # +- 3.012 pb
    group: WPlusJets
    era: '2018'
    split: 4
    
    
  W4JetsToLNu:
    db: das:/W4JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIAutumn18NanoAODv5-Nano1June2019_102X_upgrade2018_realistic_v19-v1/NANOAODSIM
    files: dascache/bTaggingEff/W4JetsToLNu_2018.dat
    generated-events: 'genEventSumw'
    cross-section: 544.3 # +- 1.656
    group: WPlusJets
    era: '2018'
    split: 4
    
        ################# data       
  MuonEG_2018A:
    db: das:/MuonEG/Run2018A-Nano1June2019-v1/NANOAOD
    files: dascache/MuonEG_2018A.dat
    group: data
    era: '2018'
    run_range: [315252, 316995]
    certified_lumi_file: https://cms-service-dqm.web.cern.ch/cms-service-dqm/CAF/certification/Collisions18/13TeV/ReReco/Cert_314472-325175_13TeV_17SeptEarlyReReco2018ABC_PromptEraD_Collisions18_JSON.txt
  
  MuonEG_2018B:
    db: das:/MuonEG/Run2018B-Nano1June2019-v1/NANOAOD
    files: dascache/MuonEG_2018B.dat
    group: data
    era: '2018'
    run_range: [317080, 319310]
    certified_lumi_file: https://cms-service-dqm.web.cern.ch/cms-service-dqm/CAF/certification/Collisions18/13TeV/ReReco/Cert_314472-325175_13TeV_17SeptEarlyReReco2018ABC_PromptEraD_Collisions18_JSON.txt
                                                                                                        
  MuonEG_2018C:
    db: das:/MuonEG/Run2018C-Nano1June2019-v1/NANOAOD
    files: dascache/MuonEG_2018C.dat
    group: data
    era: '2018'
    run_range: [319337, 320065]
    certified_lumi_file: https://cms-service-dqm.web.cern.ch/cms-service-dqm/CAF/certification/Collisions18/13TeV/ReReco/Cert_314472-325175_13TeV_17SeptEarlyReReco2018ABC_PromptEraD_Collisions18_JSON.txt
  
  MuonEG_2018D:
    db: das:/MuonEG/Run2018D-Nano1June2019_ver2-v1/NANOAOD
    files: dascache/MuonEG_2018D.dat
    group: data
    era: '2018'
    run_range: [320673, 325175]
    certified_lumi_file: https://cms-service-dqm.web.cern.ch/cms-service-dqm/CAF/certification/Collisions18/13TeV/ReReco/Cert_314472-325175_13TeV_17SeptEarlyReReco2018ABC_PromptEraD_Collisions18_JSON.txt

plotIt:
  configuration:
    width: 800
    height: 600
    luminosity-label: '%1$.2f fb^{-1} (13 TeV)'
    experiment: CMS
    extra-label: 2018Data --Work in progress
    show-overflow: true
  legend:
    position: [0.7, 0.6, 0.91, 0.91]
  groups:
    data:
      legend: data
    TTJets_DL:
      fill-color: "#9e7986"
      legend: TTJets_DL
      order: 10
    tW:
      fill-color: "#2f3c51"
      legend: tW
      order: 9
    atW:
      fill-color: "#62434f"
      legend: atW
      order: 8
    DY:
      fill-color: "#7f0000"
      legend: DY
      order: 7
    TTJets_AH:
      fill-color: "#D4D2D5"
      legend: TTJets_AH
      order: 6
    WPlusJets:
      fill-color: "#64558A"
      legend: WPlusJets
      order: 5
    TTJets_SL:
      fill-color: "#5e2036"
      legend: TTJets_SL
      order: 4
    WW:
      fill-color: "#9ADCFE"
      legend: WW
      order: 3
    ZZ:
      fill-color: "#7C818C"
      legend: ZZ
      order: 2
    WZ:
      fill-color: "#E8A53A"
      legend: WZ
      order: 1
  systematics:
      # on the jets
      - jer
      - jesTotal
      # sys from theory  
      - qcdScale
      - psISR
      - psFSR
      # on the lepton id /iso 
      - muid
      - muiso
      - muon_ID
      - muon_iso
      - ele_reco 
      - ele_ID
      # on double leptons (opposite sign, opposite flavour ) trigger 
      - elmutrig
      - mueltrig
      # on single lepton trigger 
      #- ele_trigger
      #- muon_trigger
      # on the cross section : 1+xsec_uncert(pb)/xsec(pb)
      #-TTToSemiLeptonicxsc: {type: const, value: , on: 'TTToSemiLeptonic'}
      #-TTToFullLeptonicxsc: {type: const, value: , on: 'TTToFullLeptonic'}
      - TTToHadronicxsc: {type: const, value: 1.0148209682 , on: ' TTToHadronic '}
      - ST_tW_top_5fxsc: {type: const, value: 1.00080554761 , on: ' ST_tW_top_5f '}
      - ST_tW_antitop_5fxsc: {type: const, value: 1.00000178811 , on: ' ST_tW_antitop_5f '}
      - DYJetsToLL_M-50-amcatnloFXFXxsc: {type: const, value: 1.00433297595 , on: ' DYJetsToLL_M-50-amcatnloFXFX '}
      - W2JetsToLNuxsc: {type: const, value: 1.00289079842 , on: ' W2JetsToLNu '}
      - W3JetsToLNuxsc: {type: const, value: 1.00303476071 , on: ' W3JetsToLNu '}
      - W4JetsToLNuxsc: {type: const, value: 1.00304243983 , on: ' W4JetsToLNu '}
      - WWxsc: {type: const, value: 1.00148153034 , on: ' WW '}
      - WZxsc: {type: const, value: 1.00144927536 , on: ' WZ '}
      - ZZxsc: {type: const, value: 1.00161779242 , on: ' ZZ '}
